version: "3"
services:
  frontend:
    image: my-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: my-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"